### ISSUE TITLE
Error:(96, 0) Could not find property 'bintray_user' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@cfc006b. <a href="openFile:/home/eric/AndroidStudioProjects/Android-ExpandableTextView/expandabletextview/build.gradle">Open File</a>

### ISSUE THREAD

**Issue by ericn37** [Blogcat/Android-ExpandableTextView#9]
I can't build this project

**Comment by Cliffus** [comment]
Hi

it is correct that currently, only me can build the project because bintray_user and bintray_gpg_password are private global gradle properties set on my computer. I can't share these credentials with you. To build this project on your computer, you should remove all maven / bintray related stuff from the build.gradle file.

You don't need to build the project yourself to use it for your project. You can just add the maven dependency to your project as described here: https://github.com/Blogcat/Android-ExpandableTextView/blob/master/README.md

Please let me know if you need more information to resolve your issue.
